Chat 1
awesome-academy/pr1805_winku pull request #16
Opened 2019-06-06 02:00 UTC by DuyNguyen05

2019-06-06 08:30 UTC, tunm1180 requested changes

2019-06-06 08:30 UTC, tunm1180 commented on app/helpers/conversations_helper.rb
> +module ConversationsHelper
xoá file thừa đi

2019-06-06 08:30 UTC, tunm1180 commented on app/models/conversation.rb
> +  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
User.name

2019-06-06 08:30 UTC, tunm1180 commented on app/models/conversation.rb
> +  scope :involving, -> (user) do
hàm này làm gì đây

2019-06-06 08:30 UTC, tunm1180 commented on app/models/user.rb
> +  enum role: {admin: 1, user: 2, business: 3}, _prefix: :role
?

2019-06-06 08:30 UTC, tunm1180 commented on app/models/user.rb
>    enum role: {admin: 1, user: 2, business: 3}, _prefix: :role
?

2019-06-06 09:33 UTC, DuyNguyen05 commented on app/models/user.rb
> +  enum role: {admin: 1, user: 2, business: 3}, _prefix: :role
cái enum role là của cái Thảo a ơi :1234:

2019-06-07 08:55 UTC, DuyNguyen05 commented on app/models/conversation.rb
> +  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
User thoi a oi =))

2019-06-07 09:30 UTC, tunm1180 requested changes

2019-06-07 09:30 UTC, tunm1180 commented on app/assets/stylesheets/messages.scss
> +// Place all the styles related to the messages controller here.
xoá file thừa đi em

2019-06-07 09:30 UTC, tunm1180 commented on app/models/conversation.rb
> +  belongs_to :sender, :foreign_key => :sender_id, class_name: "User"
User.name

2019-06-07 09:30 UTC, tunm1180 commented on app/models/conversation.rb
> +  belongs_to :recipient, :foreign_key => :recipient_id, class_name: "User"
same above

2019-06-07 09:30 UTC, tunm1180 commented on app/models/user.rb
> +  enum role: {admin: 1, user: 2, business: 3}, _prefix: :role
ko thấy ở dưới có 1 dòng giống hệt như này rồi à

2019-06-07 09:30 UTC, tunm1180 commented on config/private_pub.yml
> +  secret_token: "4790b9ca5ae89797ec67e4e151d5e9a5adb2815be83b86a98d0f4a6fef95eb72"
key gì cho hết vào figaro đi em

2019-06-07 13:48 UTC, tunm1180 approved these changes

2019-06-07 13:48 UTC, merged