add friend
awesome-academy/pr1805_winku pull request #25
Opened 2019-06-12 11:33 UTC by DuyNguyen05

2019-06-12 11:46 UTC, nguyenminhtu requested changes

2019-06-12 11:46 UTC, nguyenminhtu commented on app/controllers/friendships_controller.rb
> +    @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
`friend_id: params[:friend_id]`

2019-06-12 11:46 UTC, nguyenminhtu commented on app/helpers/friendships_helper.rb
> +module FriendshipsHelper
bỏ file thừa đi

2019-06-12 11:46 UTC, nguyenminhtu commented on app/models/friendship.rb
> +  belongs_to :friend, :class_name => User.name
`class_name: User.name`

2019-06-12 11:46 UTC, nguyenminhtu commented on app/views/friendships/create.js.erb
> +$("#action-<%= @friend.id %>").html("<%= j render "friendships/unfriend", user: @friend %>")
tạo friendship xong sao ko truyền luôn friendship_id xuống form unfriend đỡ trong form lại find_by

2019-06-13 07:18 UTC, DuyNguyen05 commented on app/views/friendships/create.js.erb
> +$("#action-<%= @friend.id %>").html("<%= j render "friendships/unfriend", user: @friend %>")
e render vào user index thì tìm friendship_id ở đâu ạ

2019-06-13 09:18 UTC, tunm1180 approved these changes

2019-06-13 09:18 UTC, merged