Statistical business
awesome-academy/pr1805_winku pull request #29
Opened 2019-06-16 15:10 UTC by Phuongthao12345

2019-06-16 15:13 UTC, Phuongthao12345 commented
![image](https://user-images.githubusercontent.com/36850506/59565988-f8280a80-9083-11e9-9d68-73b27d554bb3.png)

2019-06-17 01:50 UTC, tunm1180 requested changes

2019-06-17 01:50 UTC, tunm1180 commented on app/controllers/tours_controller.rb
> +      redirect_to user_path(current_user)
`redirect_to current_user` có đc ko nhỉ

2019-06-17 04:20 UTC, tunm1180 approved these changes

2019-06-17 04:21 UTC, merged