Sign_In
awesome-academy/pr1805_winku pull request #5
Opened 2019-05-22 02:56 UTC by DuyNguyen05

layout_home & layout_profile

2019-05-22 03:25 UTC, tunm1180 requested changes

2019-05-22 03:25 UTC, tunm1180 commented on app/views/static_pages/index.html.erb
> +                              <%= link_to destroy_user_session_path, method: :delete do  %>
ko check hiển thị ở đây à, nó chưa login mà vẫn thấy nút log out à

2019-05-22 03:25 UTC, tunm1180 commented on config/locales/devise.en.yml
> +en:
làm thêm 1 file tiếng việt nữa nhé

2019-05-22 03:43 UTC, DuyNguyen05 commented on app/views/static_pages/index.html.erb
> +                              <%= link_to destroy_user_session_path, method: :delete do  %>
Em quên mất h e xóa

2019-05-22 04:57 UTC, dogiadat commented on app/views/devise/confirmations/new.html.erb
> +<h2>Resend confirmation instructions</h2>
i18n

2019-05-28 00:59 UTC, tunm1180 requested changes

2019-05-28 00:59 UTC, tunm1180 commented on app/controllers/users_controller.rb
> +    @user = User.find_by params[:id]
chắc ko

2019-05-28 00:59 UTC, tunm1180 commented on app/controllers/users_controller.rb
> +  before_action :correct_user , only: [:show ,:edit, :update]
correct_user for show ?

2019-05-28 00:59 UTC, tunm1180 commented on app/views/devise/mailer/unlock_instructions.html.erb
> +<p>Hello <%= @resource.email %>!</p>
bỏ phần unlock đi em

2019-05-28 00:59 UTC, tunm1180 commented on app/views/devise/passwords/edit.html.erb
> +          <%= f.submit I18n.t (".Change_my_password") %>
`<%= f.submit t(".Change_my_password") %>`

2019-05-28 00:59 UTC, tunm1180 commented on app/views/devise/registrations/new.html.erb
> +<h2><%= I18n.t ".Sign_up" %></h2>
cái view này hình như ko dùng đúng ko

2019-05-28 00:59 UTC, tunm1180 commented on app/views/devise/unlocks/new.html.erb
> +<h2>Resend unlock instructions</h2>
bỏ phần unlock đi em

2019-05-28 01:07 UTC, DuyNguyen05 commented on app/controllers/users_controller.rb
> +    @user = User.find_by params[:id]
@user = User.find_by id: params[:id]
em dang bi conflict giua find vs find_by =))

2019-05-29 12:54 UTC, tunm1180 approved these changes

2019-05-29 12:54 UTC, merged